version: '2'
services:
    reverse-proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
            - $PROXY_HTTP_PORT:80/tcp
            - $PROXY_HTTPS_PORT:443/tcp
        volumes:
            - $DOCKER_SOCK:/tmp/docker.sock:ro