version: '2'
services:
    reverse-proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
            - $PROXY_HTTP_PORT:80/tcp
            - $PROXY_HTTPS_PORT:443/tcp
        volumes:
            - $DOCKER_SOCK:/tmp/docker.sock:ro
    mariadb:
        build: ./mariadb
        restart: always
        volumes:
            - $MARIADB_VOLUME:/var/lib/mysql
        environment:
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.6
        restart: always
        links:
            - mariadb:db
        environment:
            - VIRTUAL_HOST=$PMA_VIRTUAL_HOST